import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import localFont from 'next/font/local'

const myFont = localFont({ src: "../../public/fonts/anirb___.woff" })

import { MainContextProvider } from '@/context/lotr.context'

import { ApiContextProvider } from '@/context/api.context'

import Navbar from "./Components/Navbar/index"
import Footer from "./Components/Footer/index"

import tw from "tailwind-styled-components"

const Container = tw.div`
     w-full 
     px-16 
     py-12
`;


const Content = tw.div`
    bg-slate-200
    dark:bg-slate-700
`;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   
        <html lang="en">
          <body className={myFont.className}>

           
                {children}
             
          </body>
        </html>
 
  )
}
